FROM edgeworx/darcy-ai-sdk-base:1.0.0

RUN python3 -m pip install falconn

COPY src/face_mask_detection.tflite /src/face_mask_detection.tflite
COPY src/examples/static /src/static
COPY src/darcyai/ /src/darcyai
COPY src/people_counting_face_mask.py /src/demo.py

ENTRYPOINT ["/bin/bash", "-c", "cd /src/ && python3 ./demo.py"]
